export const ACCEPTED_PRIVACY_POLICY_KEY = "ACCEPTED_PRIVACY_POLICY_KEY";
export const EMAIL_KEY = "EMAIL_KEY";
export const TOKEN_KEY = "TOKEN_KEY";

export const DONATION_MODAL_SEEN_AT_KEY = "DONATION_MODAL_SEEN_AT_KEY";
